export const PrivacyPolicy = {
    fr: {
        title: "Politique de Confidentialité",
        lastUpdate: "Dernière mise à jour : Février 2024",
        part1Title: "1. Introduction",
        part1Content: "Xpress News s'engage à protéger votre vie privée. Cette Politique de Confidentialité explique comment nous collectons, utilisons et protégeons vos données lors de l'utilisation de notre application d'actualités.",
        part2Title: "2. Informations Collectées",
        part21Subtitle: "2.1 Préférences utilisateur :",
        part211: "Préférences de thème (mode clair/sombre)",
        part212: "Catégories d'actualités sélectionnées",
        part213: "Pays sélectionné",
        part214: "Statut d'abonnement",
        part22Subtitle: "2.2 Informations collectées automatiquement :",
        part221: "Informations sur l'appareil (modèle, système d'exploitation)",
        part222: "Données d'utilisation (articles lus, temps d'interaction)",
        part223: "Données de performance de l'application",
        part224: "Note : Nous ne collectons aucune information d'identification personnelle comme l'email, le nom ou la localisation.",
        part3Title: "3. Utilisation des Informations",
        part3Content: "Nous utilisons les informations collectées pour :",
        part31: "Personnaliser votre fil d'actualités selon vos préférences",
        part32: "Traiter vos paiements d'abonnement via les systèmes Apple/Google",
        part33: "Améliorer notre application et l'expérience utilisateur",
        part34: "Maintenir et optimiser les performances de l'application",
        part35: "Générer des statistiques d'utilisation anonymes",
        part4Title: "4. Stockage et Sécurité des Données",
        part41: "Vos préférences sont stockées localement sur votre appareil",
        part42: "Le statut d'abonnement est géré par les services Apple/Google",
        part43: "Nous ne maintenons pas de base de données utilisateurs",
        part44: "Votre historique de lecture et vos préférences restent privés",
        part5: "5. Partage des Données",
        part5Content: "Nous ne partageons aucune donnée utilisateur avec des tiers. Les seules interactions avec des services externes sont :",
        part51: "Le traitement des paiements via les systèmes officiels App Store/Play Store",
        part52: "Le contenu d'actualités provenant de nos sources sélectionnées",
        part6Title: "6. Vos Droits",
        part6Content: "Vous avez le droit de :",
        part61: "Effacer vos données locales de l'application",
        part62: "Annuler votre abonnement via les services Apple/Google",
        part63: "Nous contacter pour toute question concernant votre confidentialité",
        part7Title: "7. Nous Contacter",
        part7Content: "Pour toute question concernant la confidentialité, contactez-nous à :",
        email: "jolan.callens@gmail.com",
    },
    en: {
        title: "Privacy Policy",
        lastUpdate: "Last update: February 2024",
        part1Title: "1. Introduction",
        part1Content: "Xpress News is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and protect your data when using our news application.",
        part2Title: "2. Collected Information",
        part21Subtitle: "2.1 User Preferences:",
        part211: "Theme preferences (light/dark mode)",
        part212: "Selected news categories",
        part213: "Selected country",
        part214: "Subscription status",
        part22Subtitle: "2.2 Automatically collected information:",
        part221: "Device information (model, operating system)",
        part222: "Usage data (read articles, interaction time)",
        part223: "Application performance data",
        part224: "Note: We do not collect any personally identifiable information such as email, name, or location.",
        part3Title: "3. Use of Information",
        part3Content: "We use the collected information to:",
        part31: "Personalize your news feed according to your preferences",
        part32: "Process your subscription payments via Apple/Google systems",
        part33: "Improve our application and user experience",
        part34: "Maintain and optimize application performance",
        part35: "Generate anonymous usage statistics",
        part4Title: "4. Data Storage and Security",
        part41: "Your preferences are stored locally on your device",
        part42: "Subscription status is managed by Apple/Google services",
        part43: "We do not maintain a user database",
        part44: "Your reading history and preferences remain private",
        part5: "5. Data Sharing",
        part5Content: "We do not share any user data with third parties. The only interactions with external services are:",
        part51: "Processing payments via official App Store/Play Store systems",
        part52: "News content from our selected sources",
        part6Title: "6. Your Rights",
        part6Content: "You have the right to:",
        part61: "Erase your local application data",
        part62: "Cancel your subscription via Apple/Google services",
        part63: "Contact us for any questions regarding your privacy",
        part7Title: "7. Contact Us",
        part7Content: "For any privacy-related questions, contact us at:",
        email: "jolan.callens@gmail.com",
    },
}