export const Texts = {
    fr: {
        // Home
        home: "Accueil",
        noArticles: "Aucun article dans les catégories sélectionnées",
        moreButton: "En savoir plus",
        listenButton: "Écouter",
        // Drawer
        personalizeFeed: "Personnalise ton feed",
        settingsButton: "Paramètres",
        remainingCredits: "Crédits restants",
        upgrade: "Passer à Premium ⚡️",
        // Theme
        appearance: "Apparence",
        system: "Système",
        light: "Clair",
        dark: "Sombre",
        // Article
        articleNotFound: "Article introuvable",
        context: "Contexte",
        details: "Détails",
        issues: "Conséquences",
        conclusion: "Ce qu'il faut retenir",
        openArticle: "Consulter l'article",
        qAndA: "Q&A",
        today: "Aujourd'hui",
        yesterday: "Hier",
        // Chat
        chatInputPlaceholder: "Pose moi une question sur l'article !",
        // Bookmarks
        bookmarks: "Favoris",
        bookmarksButton: "Accéder aux favoris",
        // Language
        language: "Langue",
        french: "Français",
        english: "Anglais (US)",
        // Settings
        settings: "Paramètres",
        country: "Pays",
        france: "France",
        usa: "États-Unis",
        upgradeToXpressPremium: "Passer à Xpress Premium",
        privacyPolicy: "Politique de Confidentialité",
        // Upgrade
        upgradeTitle1: "Passer à",
        upgradeTitle1WithTrial: "Essaie",
        upgradeTitle2WithTrial: "gratuitement pendant 1 mois",
        creditsByMonth: "200 crédits / mois",
        accessBookmarks: "Accès aux favoris",
        annualSubscription: "Annuel",
        monthlySubscription: "Mensuel",
        annualSubscriptionDescription: "par an",
        monthlySubscriptionDescription: "par mois",
        annualSubscriptionTrialDescription: "par an après 1 mois d'essai",
        monthlySubscriptionTrialDescription: "par mois après 1 mois d'essai",
        discount: "ÉCONOMISEZ 20%",
        subscriptionButton: "Passer à Premium ⚡️",
        subscriptionTrialButton: "Commencer l'essai gratuit ⚡️",
        subscriptionInfo: "Vous serez facturé XX.XX par UU. Vous pouvez annuler à tout moment.",
        subscriptionTrialInfo: "Vous serez facturé XX.XX par UU après la fin de votre essai gratuit de 1 mois. Vous pouvez annuler à tout moment.",
        subscriptionAlreadySubscribedAlertTitle: "Déjà abonné",
        subscriptionAlreadySubscribedAlertMessage: "Vous êtes déjà abonné à Xpress Premium",
        year: "an",
        month: "mois",
        // Errors
        error: "Erreur",
        errorFetchingArticles: "Erreur lors de la récupération des articles",
        errorFetchingChatbotResponse: "Erreur lors de la récupération de la réponse du chatbot",
        errorInsufficientCredits: "Crédits insuffisants",
        errorInsufficientCreditsChatbotMessage: "Vous n'avez plus de crédits pour utiliser le chatbot",
        errorInsufficientCreditsListenMessage: "Vous n'avez plus de crédits pour écouter l'article",
        // Credits
        credits: "Crédits",
        creditsTitle: "Comprendre les crédits",
        whatAreCredits: "Qu'est-ce que les crédits ?",
        creditsExplanation: "Les crédits sont votre monnaie pour accéder aux fonctionnalités avancées de l'application. Ils vous permettent d'utiliser le chatbot pour poser des questions sur les articles et d'écouter le résumé des articles en audio. Tous les premiers du mois, des crédits sont ajoutés sur votre compte.",
        howToUseCredits: "Comment utiliser vos crédits ?",
        chatbotUsage: "1 crédit par message avec le chatbot",
        listenUsage: "1 crédit pour écouter un article",
        monthlyCredits: "Crédits mensuels",
        freePlan: "Gratuit",
        premiumPlan: "Premium",
        creditsPerMonth: "crédits par mois",
        upgradeToPremium: "Passer à l'offre Premium",
        // Subscription modal
        premiumOffer: "Passez à l'offre Premium",
        premiumFeature1Title: "200 crédits mensuels",
        premiumFeature1Description: "Profitez de 200 crédits chaque mois pour utiliser le chatbot et écouter les résumés",
        premiumFeature2Title: "Sans engagement",
        premiumFeature2Description: "Annulez votre abonnement à tout moment",
        premiumFeature3Title: "Fonctionnalités exclusives",
        premiumFeature3Description: "Accédez en avant-première aux nouvelles fonctionnalités",
        seeOffers: "Voir les offres",
    },
    en: {
        // Home
        home: "Home",
        noArticles: "No articles in selected categories",
        moreButton: "Read more",
        listenButton: "Listen",
        // Drawer
        personalizeFeed: "Personalize your feed",
        settingsButton: "Settings",
        remainingCredits: "Remaining credits",
        upgrade: "Upgrade to Premium ⚡️",
        // Theme
        appearance: "Appearance",
        system: "System",
        light: "Light",
        dark: "Dark",
        // Article
        articleNotFound: "Article not found",
        context: "Context",
        details: "Details",
        issues: "Issues",
        conclusion: "What to remember",
        openArticle: "Open the article",
        qAndA: "Q&A",
        today: "Today",
        yesterday: "Yesterday",
        // Chat
        chatInputPlaceholder: "Ask me a question about the article !",
        // Bookmarks
        bookmarks: "Bookmarks",
        bookmarksButton: "Access bookmarks",
        // Language
        language: "Language",
        french: "French",
        english: "English (US)",
        // Settings
        settings: "Settings",
        country: "Country",
        france: "France",
        usa: "United States",
        upgradeToXpressPremium: "Upgrade to Xpress Premium",
        privacyPolicy: "Privacy Policy",
        // Upgrade
        upgradeTitle1: "Upgrade to",
        upgradeTitle1WithTrial: "Try",
        upgradeTitle2WithTrial: "free for 1 month",
        creditsByMonth: "200 credits / month",
        accessBookmarks: "Access to bookmarks",
        annualSubscription: "Annual",
        monthlySubscription: "Monthly",
        annualSubscriptionDescription: "per year",
        monthlySubscriptionDescription: "per month",
        annualSubscriptionTrialDescription: "per year after 1 month trial",
        monthlySubscriptionTrialDescription: "per month after 1 month trial",
        discount: "SAVE 20%",
        subscriptionButton: "Upgrade to Premium ⚡️",
        subscriptionTrialButton: "Start 1 month free trial ⚡️",
        subscriptionInfo: "You’ll be charged XX.XX per UU. You can cancel anytime.",
        subscriptionTrialInfo: "You’ll be charged XX.XX per UU after your 1 month free trial ends. You can cancel anytime.",
        subscriptionAlreadySubscribedAlertTitle: "Already subscribed",
        subscriptionAlreadySubscribedAlertMessage: "You are already subscribed to Xpress Premium",
        year: "year",
        month: "month",
        // Errors
        error: "Error",
        errorFetchingArticles: "Error while fetching articles",
        errorFetchingChatbotResponse: "Error while fetching chatbot response",
        errorInsufficientCredits: "Insufficient credits",
        errorInsufficientCreditsChatbotMessage: "You don't have enough credits to use the chatbot",
        errorInsufficientCreditsListenMessage: "You don't have enough credits to listen to the article",
        // Credits
        credits: "Credits",
        creditsTitle: "Understanding Credits",
        whatAreCredits: "What are credits?",
        creditsExplanation: "Credits are your currency to access advanced features in the application. They allow you to use the chatbot to ask questions about articles and listen to articles summaries in audio. Every first of the month, credits are added to your account.",
        howToUseCredits: "How to use your credits?",
        chatbotUsage: "1 credit per chatbot message",
        listenUsage: "1 credit to listen to an article",
        monthlyCredits: "Monthly Credits",
        freePlan: "Free",
        premiumPlan: "Premium",
        creditsPerMonth: "credits per month",
        upgradeToPremium: "Upgrade to Premium",
        // Subscription modal
        premiumOffer: "Upgrade to Premium",
        premiumFeature1Title: "200 monthly credits",
        premiumFeature1Description: "Get 200 credits every month to use the chatbot and listen to summaries",
        premiumFeature2Title: "No commitment",
        premiumFeature2Description: "Cancel your subscription anytime",
        premiumFeature3Title: "Exclusive features",
        premiumFeature3Description: "Get early access to new features",
        seeOffers: "See offers",
    }
}